-- Here are a bunch of
-- silly MYSQL statements
-- That could have been generated by a dump

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  id int(11) NOT NULL AUTO_INCREMENT,
  email varchar(60) NOT NULL,
  password varchar(128) NOT NULL,
  displayname varchar(255),
  PRIMARY KEY (id)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

   /* random indentation and comment! */ INSERT INTO user (email,password,displayname) VALUES ('blah@blah.com','password;with;semicolons!','blah');

INSERT INTO user (email,password,displayname) VALUES ("bl;ah%blah@blah.com","

this is a wacky password;
that span;s several lines with embeded semi-colons!

","blah"); /* skip this ending comment? */

INSERT INTO user (email,password,displayname) VALUES (blah@blah.com,blah,blah); /* this is an invalid MYSQL statement */
